version: "3"
services:
  backend:
    build: .
    ports:
      - 80:8000
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app
    depends_on:
      - sqlite
  
  sqlite:
    image: nouchka/sqlite3
    volumes:
      - db-data:/db

  frontend:
    image: nginx:alpine
    volumes:
      - ./frontend/static:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf
      - /etc/letsencrypt:/etc/letsencrypt
    ports:
      - 8080:80
      - 443:443
    depends_on:
      - backend
  
volumes:
  db-data: