version: "3"
services:
  backend:
    build: .
    ports:
      - 80:8000
    env_file:
      - ./.env
    depends_on:
      - sqlite
  
  sqlite:
    image: nouchka/sqlite3
    volumes:
      - db-data:/db
volumes:
  db-data: